spring:
  security:
    user:
      name: user
      password: afonso123
  profiles:
    active: mysql
  application:
    name: spring-boot-trench
  datasource:
    url: jdbc:mysql://localhost:3307/user_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: mysql123
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: false

  threads:
    virtual:
      enabled: true
server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    #org.hibernate.orm.jdbc.bind: trace
    net.ttddyy.dsproxy.listener: debug
    org.hibernate.SQL: OFF

decorator:
  datasource:
    datasource-proxy:
      format-sql: true
      slow-query:
        threshold: 1000
